<Project Sdk="Microsoft.NET.Sdk">
  <PropertyGroup><TargetFramework>net472</TargetFramework><LangVersion>latest</LangVersion><GamePath Condition="'$(GamePath)' == ''">C:\Program Files (x86)\Steam\steamapps\common\Valheim</GamePath></PropertyGroup>
  <ItemGroup>
    <ProjectReference Include="..\KneeSlapperFreeze.csproj" />
    <Reference Include="BepInEx"><HintPath>$(GamePath)\BepInEx\core\BepInEx.dll</HintPath><Private>false</Private></Reference>
    <Reference Include="0Harmony"><HintPath>$(GamePath)\BepInEx\core\0Harmony.dll</HintPath><Private>false</Private></Reference>
    <Reference Include="assembly_valheim"><HintPath>$(GamePath)\valheim_Data\Managed\assembly_valheim.dll</HintPath><Private>false</Private></Reference>
    <Reference Include="assembly_utils"><HintPath>$(GamePath)\valheim_Data\Managed\assembly_utils.dll</HintPath><Private>false</Private></Reference>
    <Reference Include="assembly_guiutils"><HintPath>$(GamePath)\valheim_Data\Managed\assembly_guiutils.dll</HintPath><Private>false</Private></Reference>
    <Reference Include="$(GamePath)\valheim_Data\Managed\UnityEngine*.dll"><Private>false</Private></Reference>
  </ItemGroup>
</Project>
